### ISSUE TITLE
Create a map

### ISSUE THREAD

**Issue by mlane3** [mlane3/unitedway#18]
We need to create a map after we join the data.  This is because united way really want to see there data like a map.

To join the data we need to so we need to complete this objective.

**Comment by mlane3** [comment]
It needs to have color

**Comment by BrianGHerbert** [comment]
I am beginning work on the data frame for county values, and I thought of this map piece and want to state my assumption of how map component will use county data frame (and zip data frame):
1.  I expect we will have a 13 county x (14 measure + 3 pillar + 1 CWBI) data frame, the map will need to be able to pull from that to color based on user selection.  EX. user selects "community" index toggle, map lights up with colors for community index value for each county
2.  I expect the next drill down will ,have an approx 150 Zip (?) x (14 measure + 3 pillar + 1 CWBI) data frame, the map will need to light up zips based on user selected measure.

Y'all may have discussed this directly, but wanted to chime in to make sure all our assumptions are in synch.

**Comment by mlane3** [comment]
Yes your assumptions are correct, :)

**Comment by mlane3** [comment]
So what we need left to do is add labels and a legend. @bglover3000 you been working hard on it.  I felt like you could leave some of your notes here if you wanted to add to how the map works :)

**Comment by bglover3000** [comment]
Map notes (Things that are needed):
1.) Display of the correct county on label (also not sure if we wanted an underlying label on the map)
2.) Legend- currently working on errors to get it displayed
.....I will continue to update here as I come across additional things that are needed.

**Comment by mlane3** [comment]
We did it.  The leaflet map works and displays everything we need.  If united way needs more, we will do it in another project.
